# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      HashtagCloudCo\AdminBundle\Entity\users: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        Hashtag_db_provider:
            entity:
                class: HashtagCloudCoAdminBundle:users
                property: username



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic: ~
            pattern: ^/
            provider: Hashtag_db_provider
            anonymous: ~
            form-login:
                login_path: login
                check_path: login
                default_target_path: /post
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate



            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: '^/post',roles: ROLE_USER}
        - { path: '^/admin', roles: ROLE_ADMIN}

#    access_control:
#            # require ROLE_ADMIN for /admin*
#        - { path: ^/admin, roles: ROLE_ADMIN }