services:
#    hashtag_cloud_co_admin.example:
#        class: HashtagCloudCo\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  HashtagCloudCo\AdminBundle\Controller\RegistrationController:
     autowire: true # or define your controller constructor and configure its arguments explicitly
     tags: ['controller.service_arguments']

#  HashtagCloudCo\AdminBundle\Controller\LoginController:
#     public: true
#     bind:
#       $authenticationUtils: '@security.authentication_utils'

  HashtagCloudCo\AdminBundle\Controller\LoginController:
      public: true
      tags: ['controller.service_arguments']
      bind:
        $authenticationUtils: '@security.authentication_utils'

